#!/usr/bin/perl
use App::RL;

App::RL->run;

=head1 OVERVIEW

For help with App::RL, run "runlist help"

=cut

__END__

perl -I lib/ script/runlist

perl -I lib/ script/runlist merge t/I.yml t/II.yml -o stdout

perl -I lib/ script/runlist stat t/intergenic.yml -s t/chr.sizes -o stdout

perl -I lib/ script/runlist compare --op intersect t/intergenic.yml t/repeat.yml -o stdout

perl -I lib/ script/runlist split t/repeat.yml -o stdout

perl -I lib/ script/runlist genome t/chr.sizes -o stdout
perl -I lib/ t/07-genome.t

perl -I lib/ script/runlist combine t/Atha.yml -o stdout

perl -I lib/ script/runlist some t/Atha.yml t/Atha.list -o stdout

perl -I lib/ script/runlist covers t/S288c.txt -o stdout
perl -I lib/ t/11-covers.t

perl -I lib/ script/runlist compare t/all-gene.yml t/paralog.yml --op intersect -o all-gene-paralog.yml

perl ~/Scripts/egas/compare_runlist.pl --op intersect -f1 t/intergenic.yml -f2 t/repeat.yml
