#!/usr/bin/perl
use App::RL;

App::RL->run;

=head1 OVERVIEW

For help with App::RL, run "runlist help"

=cut

__END__

perl -I lib/ script/runlist

perl -I lib/ script/runlist merge t/I.yml t/II.yml -o stdout

perl -I lib/ script/runlist stat t/intergenic.yml -s t/chr.sizes -o stdout
